### ISSUE TITLE
harmonize 'book' and 'book_short'

### ISSUE THREAD

**Issue by tonyjurg** [saulocantanhede/tfgreek2#3]
should the feature book_short and book not be interchangeble? Now 'book' is on 9 node types, and 'book_short' on only two
https://github.com/saulocantanhede/tfgreek2/blob/main/docs/doc4TF/book_short.md
https://github.com/saulocantanhede/tfgreek2/blob/main/docs/doc4TF/book.md

**Comment by saulocantanhede** [comment]
It was updated.
