### ISSUE TITLE
Question: should Feature: after include all critical markers?

### ISSUE THREAD

**Issue by tonyjurg** [saulocantanhede/tfgreek2#5]
https://github.com/saulocantanhede/tfgreek2/blob/main/docs/doc4TF/after.md

**Comment by saulocantanhede** [comment]
The _after_ feature is defined with the characters presented after the text of the word obtained from the XML data, including punctuation symbols and critical markers.

![image](https://github.com/saulocantanhede/tfgreek2/assets/121267518/7cf97cfd-56e3-4a26-9203-167a990339ef)

**Comment by tonyjurg** [comment]
Thanks. Its clear. I've adopted the documentation.
