### ISSUE TITLE
where does data for nodeId originate from?

### ISSUE THREAD

**Issue by tonyjurg** [saulocantanhede/tfgreek2#6]
https://github.com/saulocantanhede/tfgreek2/blob/main/docs/features/nodeId.md

**Comment by saulocantanhede** [comment]
The information that I have comes from this source:

https://github.com/Clear-Bible/macula-greek/blob/main/doc/MACULA%20Greek%20Treebank%20for%20the%20Nestle%201904%20Greek%20New%20Testament.pdf

![image](https://github.com/saulocantanhede/tfgreek2/assets/121267518/5a5a1f5c-ee99-47bc-a89e-9f374c9ffd8a)
