### ISSUE TITLE
where does data for feature note originate from?

### ISSUE THREAD

**Issue by tonyjurg** [saulocantanhede/tfgreek2#7]
https://github.com/saulocantanhede/tfgreek2/blob/main/docs/features/note.md

**Comment by saulocantanhede** [comment]
It appears only once in the XML data in Acts 7:7. I think it could be the same issue as the tag _error_, which occurs only once.

![image](https://github.com/saulocantanhede/tfgreek2/assets/121267518/867d250a-40b0-4a30-b6e9-4df536b8cf63)

**Comment by tonyjurg** [comment]
I see in Acts XML data @ Line 67070: note="discontinuous discourse">εἶπεν</w>

**Comment by tonyjurg** [comment]
doc updated
